Add ability to deploy to quay on release
pmorie/osb-starter-pack pull request #101
Opened 2018-05-18 18:25 UTC by shawn-hurley

2018-05-18 18:50 UTC, lilic requested changes
When does deploy get triggered? On every PR merge?

2018-05-18 18:50 UTC, LiliC commented on .travis.yml
> +depoloy:
think this might be a typo: deploy?

2018-05-18 18:57 UTC, shawn-hurley commented on .travis.yml
> +depoloy:
🤦‍♂️

2018-05-18 19:11 UTC, pmorie reviewed
We need to make sure the travis robot has access to the quay repository, right?

2018-05-21 18:03 UTC, shawn-hurley commented
@pmorie I believe that I have added the access and the environment variables to travis

2022-04-27 13:53 UTC, closed without merging